language: node_js
node_js:
  - "4.2"
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
after_success:
  - npm run karma
  - npm run combine
  - npm run coveralls
  - npm run codacy
  - npm run codeclimate