language: node_js
node_js:
  - "8"
script:
  - npm test
  - npm run build
after_success:
  - npm run coveralls
  - npm run codacy
  - npm run codeclimate
deploy:
  - provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token:
    secure: $GITHUB_TOKEN
  on:
    branch: master

  - provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file:
    - "dist/crypto-api.js"
    - "dist/crypto-api.min.js"
    - "dist/crypto-api.min.js.map"
  skip_cleanup: true
  on:
    tags: true

  - provider: npm
  email: "nf404.name@gmail.com"
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: true
